### ISSUE TITLE
problems with the screen

### ISSUE THREAD

**Issue by thiccraymond** [ninjamuffin99/Funkin#46] opened 2020-12-09 21:16 UTC
appears cut off[
![Captura de pantalla (110)](https://user-images.githubusercontent.com/75757974/101688337-7f63fd80-3a31-11eb-80ed-6722e5f47d85.png)
![Captura de pantalla (109)](https://user-images.githubusercontent.com/75757974/101688352-84c14800-3a31-11eb-9074-77105728c96e.png)

](url)

**Comment by ninjamuffin99** [comment] 2020-12-22 01:16
I think this is a duplicate of #29 so imma close this one off!

**Closed by ninjamuffin99** 2020-12-22 01:16 UTC
